### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by lilydjwg** [DWCarrot/voxelmap-cache-render#1]
```
>>> RUST_BACKTRACE=1 ./voxelmap_cache_renderer render --input_dir ~/.local/share/multimc/instances/1.16.2/.minecraft/voxelmap/cache/xxx/overworld --output_dir xxx
thread 'work-0' panicked at 'index out of bounds: the len is 108 but the index is 16447', src/render.rs:180:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:62
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/application.rs:140:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/option.rs:1221
   3: voxelmap_cache_renderer::main
```

**Comment by tcdw** [comment]
Oh yeah, I encountered the same problem... on macOS Big Sur (when I compiled this by myself).

```
RUST_BACKTRACE=full ./voxelmap_cache_renderer render --input_dir /Applications/MultiMC.app/Contents/MacOS/instances/Fabric\ 1.16.4/.minecraft/voxelmap/cache/play.nyaacat.com/world/overworld --output_dir out
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/application.rs:166:53
stack backtrace:
   0:        0x1047a191e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0afb3dc3ec8cd05f
   1:        0x1047d356e - core::fmt::write::h39441ef24fae20ea
   2:        0x1047a16b9 - std::io::Write::write_fmt::h2ffecc964e3c3ddd
   3:        0x1047bdae5 - std::panicking::default_hook::{{closure}}::h1a491655bcf6394f
   4:        0x1047bd80c - std::panicking::default_hook::h038c301fad559a62
   5:        0x1047bdff5 - std::panicking::rust_panic_with_hook::h489020cfd35413ea
   6:        0x1047a213b - std::panicking::begin_panic_handler::{{closure}}::he498abc45ca35fbf
   7:        0x1047a1a98 - std::sys_common::backtrace::__rust_end_short_backtrace::h4a2a0fae6b0989d8
   8:        0x1047bdbd3 - _rust_begin_unwind
   9:        0x1047e1fbf - core::panicking::panic_fmt::h0003130af3c08aa0
  10:        0x1047e2035 - core::result::unwrap_failed::hbfeca77107a6ab03
  11:        0x10411ca4f - core::result::Result<T,E>::unwrap::h48a008711ce9996d
                               at /private/tmp/rust-20201214-24807-12wq99b/rustc-1.47.0-src/library/core/src/result.rs:973
  12:        0x104141109 - voxelmap_cache_renderer::application::build_colormanager::h4696ca326e2e5104
                               at /Users/tcdw/Projects/voxelmap-cache-render/src/application.rs:166
  13:        0x10413ff22 - voxelmap_cache_renderer::application::Application::new::h422cacfbc7141b14
                               at /Users/tcdw/Projects/voxelmap-cache-render/src/application.rs:77
  14:        0x1040fc45a - voxelmap_cache_renderer::main::h4c24d7907d5a1de6
                               at /Users/tcdw/Projects/voxelmap-cache-render/src/main.rs:196
  15:        0x1040ea41e - core::ops::function::FnOnce::call_once::h5b5471f3c900c4bc
                               at /private/tmp/rust-20201214-24807-12wq99b/rustc-1.47.0-src/library/core/src/ops/function.rs:227
  16:        0x10411ae51 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0ab57b71133dda63
                               at /private/tmp/rust-20201214-24807-12wq99b/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:137
  17:        0x104121c04 - std::rt::lang_start::{{closure}}::h01561bff306aeaa6
                               at /private/tmp/rust-20201214-24807-12wq99b/rustc-1.47.0-src/library/std/src/rt.rs:66
  18:        0x1047be31c - std::rt::lang_start_internal::h0a88825a8a52fb96
  19:        0x104121be1 - std::rt::lang_start::h164b8668d2bedf4a
                               at /private/tmp/rust-20201214-24807-12wq99b/rustc-1.47.0-src/library/std/src/rt.rs:65
  20:        0x1040fd1c2 - _main
```

(I am using `rustc 1.47.0` on `macOS Big Sur 11.0.1 20B50 x86_64`.)

**Comment by DWCarrot** [comment]
> 
> 
> ```
> >>> RUST_BACKTRACE=1 ./voxelmap_cache_renderer render --input_dir ~/.local/share/multimc/instances/1.16.2/.minecraft/voxelmap/cache/xxx/overworld --output_dir xxx
> thread 'work-0' panicked at 'index out of bounds: the len is 108 but the index is 16447', src/render.rs:180:10
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:483
>    1: core::panicking::panic_fmt
>              at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:85
>    2: core::panicking::panic_bounds_check
>              at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:62
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/application.rs:140:23
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/std/src/panicking.rs:483
>    1: core::panicking::panic_fmt
>              at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/panicking.rs:85
>    2: core::option::expect_none_failed
>              at /rustc/d006f5734f49625c34d6fc33bf6b9967243abca8/library/core/src/option.rs:1221
>    3: voxelmap_cache_renderer::main
> ```

yeah, it seems that voxelmap in 1.16.4 makes a breaking change in cache storage so it requires some time to fix that.


besides, for @tcdw , there are some files in `py/` to be copyed to resource folder under the location of executable file:
>./
> voxelmapcache.exe
> resource/
>       biome.json
>       foliage.png
>       grass.png
>       index.json
>       colormap.png
>       weightmap.png

and py/pickup.py can be used to do that, with `python py/pickup.py <folder of executable file>`

**Comment by DWCarrot** [comment]
I find out that
in 1.15 voxelmap the cache data matrix is formed by [256(x) x 256(z) x 18]
but in 1.16 it changes to [18 x 156(z) x 156(z)]
(I have no ideal what these changes made for ...

**Comment by tcdw** [comment]
I just figured out I didn't copy all of required files into the directory, and the program is not supporting 1.16.4 map format yet.

And thanks for your patient reply!

**Comment by DWCarrot** [comment]
fixed!
(I'm scared for Github‘s issue-auto-close from commit message)
